const PAYMENT_STATUS = {
	PENDING: "PENDING",
	PAID: "PAID",
};

const PAYMENT_METHOD = {
	CASH: "CASH",
	PAY_PAL: "PAY_PAL",
	CREDIT_CARD: "CREDIT_CARD",
};

const ORDER_BY = {
	SYSTEM: "SYSTEM",
	HOTEL: "HOTEL",
};

export { PAYMENT_STATUS, PAYMENT_METHOD, ORDER_BY };
