@url_dev=http://localhost:3055/api/public/auth


#### signup
POST {{url_dev}}/sign-up
Content-Type: application/json

{
    "email" : "long@gmail.com",
    "password": "12345678"
}

#### signin
POST {{url_dev}}/sign-in
Content-Type: application/json

{
    "email" : "long@gmail.com",
    "password": "12345678"
}



### get refresh token

POST {{url_dev}}/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiMGRhYThhYi0yNDE3LTRlNDgtODUyZS1hMWFmODMyZGVmOGMiLCJlbWFpbCI6ImxvbmdAZ21haWwuY29tIiwiaWF0IjoxNzE5MTY0MTY0LCJleHAiOjE3MTk3Njg5NjR9.kBNRSmNAzZllLUfvswmLu0vWhIm4sTDr3SNSjcbKNiE"
}

